contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #variantcall channel"
    url: https://nfcore.slack.com/channels/variantcall
    about: Discussion about the nf-core/variantcall pipeline
